### PR TITLE
clear filters works and only allows for one event to be selected

### PR DESCRIPTION
**Pull request by Jennifer-Vazquez**

### CODE REVIEW

**Comment by mayuriprasad** [comment]
Looks great! Also I'm using the GitHub app so lmk if this comment isn't in the right place haha

**Review by mayuriprasad — APPROVED** [review]
great job jen!

**Review by CScheuerman — APPROVED** [review]
looks great Jen! thank you!!!

**Review by AnnaReid22 — APPROVED** [review]
well done Jen!! Looks great!!

**Pull request merged**
