### PR TITLE
encrypting passwords

### PR DESCRIPTION
**Pull request by CScheuerman**

### CODE REVIEW

**Comment by CScheuerman** [comment]
Tests for encrypting passwords is working, but a todo list test is failing

**Comment by AnnaReid22** [comment]
> Tests for encrypting passwords is working, but a todo list test is failing

Yeah, that's the one test that I'm not sure how to fix. I'll think about maybe changing it to the number of responses so it will be easier to update? Or maybe just checking the response code to make it more general and so we won't have to worry about the test every time. I'll work on this after my midterm this morning!

**Review by mayuriprasad — APPROVED** [review]
lgtm!

**Review by AnnaReid22 — APPROVED** [review]
Looks amazing good job <3

**Review by Jennifer-Vazquez — APPROVED** [review]
Nice work!

**Pull request merged**
