### PR TITLE
Added Completed TD page and button routes

### PR DESCRIPTION
**Pull request by Jennifer-Vazquez**

### CODE REVIEW

**Comment by Jennifer-Vazquez** [comment]
sorry yall, i copied the todo list and deleted stuff but had to delete all the dependencies. MY BAD

**Review by CScheuerman — APPROVED** [review]
thanks for doing this Jen, it looks good!!

**Comment by Jennifer-Vazquez** [comment]
Test

**Comment by mayuriprasad** [comment]
simply iconic lgtm

**Review by AnnaReid22 — COMMENTED** [review]
Looks awesome!!

**Pull request merged**
